services:
  # Frontend Monitoring Dashboard
  - type: web
    name: ccit-invoice-processor
    env: python
    buildCommand: |
      pip install -r crewai_outlook/requirements.txt
      cd frontend
      pip install -r requirements.txt
    startCommand: |
      cd frontend
      python app.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_SECRET_KEY
        generateValue: true

  # Daily Processing Cron Job
  - type: cron
    name: ccit-daily-processor
    env: python
    schedule: "0 9 * * 1-5"
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      python scheduler/standalone_processor.py
